appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FM114Vw/S695AUx37q7sYil8U4BY4n3E8X7WYeKXzUlSC/8pLsxm4wqIL4rSsarWh2sKIv2BzjAiReJ33oCXKi7ZNLLgqRBnRf9+CrpkHyjyfH36o9EDT8yirQ/CYq3WdeQ2ODIJyKazE2CSc84jcly+g+Nnhjcq1dGkojtSdPplcmQwr0BfaZLTDyPMxtG/t17MP16Ip39gggU1pN0crW2+p5Z5b6a+q18Fo4nr6HrMhri69YaZUGDMQpUys2cLQ461RgfqPti3CfjpCsdrlOtqBOVznXCrbwd2LdjixTn1LJn6k2I+ewMvsqxBnm1d++yOXAnPUB8Wi5EuXkZBxmaR8mrEXZCz1k2/jX1OwYAujfG3PWNgc0cQ2L2+Ii/aNA3HYvBJEPL32E0/SDb3nhoAB7ZuRnes/O8Xc5+HshpkbW6ryo9Y1YtVN5NrQu5BKkTKKmQ64vQsnWIPZnzI6cofqZGUBDS44aYu4Y3xxDz8dWMr0todOAnDClC567HDA7uOpnKhRGsGPaScFT3EB3n+eC8a+ZFCcAPmUqEFb+3QneCQUutLwv4ILHfhvvasnFbuHWfXmdCzzkV4lbQMmwYMkcSFn6O0Ios+chkzfO6fbapyhHEMBkE5lzors/jmVVzdXJQLA7gVZoVQe0qxafmbekGw5RQQiAjjdLa+dwA=
conda_forge_output_validation: false
